# Terraform Workflow for GCP CloudBuild
  
steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
      
- id: 'tf init'
  name: 'hashicorp/terraform:1.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
        terraform init
        
# [START tf-format]
- id: 'tf format'
  name: 'hashicorp/terraform:1.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        terraform fmt
        
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        cd /workspace
        ls -R
        terraform plan -var-file="examples/terraform.tfvars"
        
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        cd /workspace
        if [[ "$BRANCH_NAME" == "main" ]]; then
        terraform apply -var-file="examples/terraform.tfvars" -auto-approve
        else
          echo "Code is not merged to the main branch. Skipping Terraform Apply"
        fi
options:
  logging: CLOUD_LOGGING_ONLY  
