
steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:1.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
        terraform init
        
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        pwd
        cd /workspace
        ls -R
        terraform plan -var-file="workspace/examples/terraform.tfvars"
        
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        cd examples/     
        terraform apply -var-file="workspace/examples/terraform.tfvars" -auto-approve
options:
  logging: CLOUD_LOGGING_ONLY  
